name: Hourly Workflow

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches: main
  workflow_dispatch:

jobs:
  hourly-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # The R version to download (if necessary) and use.
 
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
            packages:
               any::knitr
               any::rmarkdown
               any::dplyr
               any::ggplot2
               any::lubridate
               any::googledrive
               any::data.table
               any::tidyr
               any::gt
               any::tictoc
               any::plotly
               any::tidyverse
 
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Render document
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: A7.qmd
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit
        run: |
          git add .
          git commit -m "Updated report"
          git push origin main
